# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aws-sdb}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Dysinger"]
  s.date = %q{2009-08-25}
  s.description = %q{}
  s.email = %q{hubert.lepicki@amberbit.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "lib/aws_sdb.rb",
     "lib/aws_sdb/error.rb",
     "lib/aws_sdb/service.rb",
     "spec/aws_sdb/service_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/hubertlepicki/aws-sdb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Amazon SimpleDB with Ruby}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/aws_sdb/service_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
